# Compile Code, Unit Test, Dependency Scan, Static Analysis Scan, Build Image, Vulnerability Scan, Deploy Image to DockerHub
version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.4.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./gradlew clean build -x test
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./gradlew clean build
      - run:
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  dependency-scan:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./gradlew dependencyCheckAnalyze
  quality-scan:
    docker:
      - image: circleci/openjdk:11-jdk
    parameters:
      sonar_key:
        type: string
      sonar_org:
        type: string
      sonar_url:
        type: string
      sonar_token:
        type: string
    steps:
      - checkout
      - run:
          command: |
            if [[ ! -z $CIRCLE_PULL_REQUEST ]];
            then
              ./gradlew sonarqube -Dsonar.projectKey=<<parameters.sonar_key>> -Dsonar.organization=<<parameters.sonar_org>> -Dsonar.host.url=<<parameters.sonar_url>> -Dsonar.login=<<parameters.sonar_token>> -Dsonar.pullrequest.key=${CIRCLE_PULL_REQUEST##*/} -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} -Dsonar.pullrequest.base=master --info
            fi
  create-image:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: 'docker build -t "aaronilovici/circletestrepo:1.0.test" .'
      - run: mkdir -p workspace
      - run:
          command: 'docker save aaronilovici/circletestrepo:1.0.test > workspace/circle-test_latest.tar'
      - persist_to_workspace:
          root: workspace
          paths:
            - circle-test_latest.tar
  image-scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: 'ls -al /tmp/workspace'
      - run:
          command: 'docker load -i /tmp/workspace/circle-test_latest.tar'
      - anchore/analyze_local_image:
          dockerfile_path: ./Dockerfile
          image_name: 'aaronilovici/circletestrepo:1.0.test'
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
          policy_failure: true
          timeout: '500'
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports
  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: 'ls -al /tmp/workspace'
      - run:
          command: 'docker load -i /tmp/workspace/circle-test_latest.tar'
      - run:
          command: 'docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}'
      - run:
          command: 'docker push docker.io/aaronilovici/circletestrepo:1.0.test'

workflows:
  fullrun:
    jobs:
      - build
      - test:
          requires:
            - build
      - dependency-scan:
          requires:
            - test
      - quality-scan:
          requires:
            - test
          sonar_key: aaronilovici_circle-test
          sonar_org: aaronilovici
          sonar_url: https://sonarcloud.io
          sonar_token: ${SONAR_TOKEN}
      - create-image:
          requires:
            - test
      - image-scan:
          requires:
            - create-image
      - hold:
          type: approval
          requires:
            - image-scan
      - deploy:
          requires:
            - hold
